### ISSUE TITLE
umd.js file still does not include css when use vite build --watch

### ISSUE THREAD

**Issue by wangmerry** [marco-prontera/vite-plugin-css-injected-by-js#144]
# **💉 Failing Test**

## **Which jobs/test(s) are failing**

*

---

## **Reason for failure/description**

---

### **Media prove**

---

### **Additional context**

*

**Comment by wangmerry** [comment]
because I used plugin vite-plugin-windicss

**Comment by waelbettayeb** [comment]
I can confirm that it's not working on watch mode when there's multiple format

**Comment by marco-prontera** [comment]
When using the --watch option the build run in a different manner, and I think this is a bug of Vite.js since the purpose of the --watch is only to have the "autoupdate". I tried to fix this, but the css file is compiled only for one step and this is random, so this means that I can't get this thing in the building process. Maybe you can open an issue to the Vite project for that.
