### ISSUE TITLE
Not support vue sfc <style scoped>

### ISSUE THREAD

**Issue by GreatAuk** [Marco-Prontera/vite-plugin-css-injected-by-js#51]

**Comment by Marco-Prontera** [comment]
@meixger Hi! 😉 This is not a bug of this plugin. This plugin applies logic only during the build phase. What caused that problem is the following code: 
`vue({
    customElement: true, template: {
      compilerOptions: {
        isCustomElement: tag => tag.includes("- ")
      }
    }
  })`
In fact, if you try to remove the `cssInjectedByJsPlugin` plugin, the button is still unstyled. I tried it locally.
Hope it's useful for you.
