### ISSUE TITLE
Incompatibility with vuetify

### ISSUE THREAD

**Issue by plaskbar** [marco-prontera/vite-plugin-css-injected-by-js#92]
Hi, 

I am having a very minimalistic setup with vuetify and your plugin, I have scaffolded the project, added those two plugins, and the `vite.config.ts` looks like this: 

```
export default defineConfig({
  plugins: [
    vue(),
    vueJsx(),
    vuetify({
      autoImport: true,
      /* avoid changes to sass config if possible
      styles: {
        configFile: 'src/theme/settings.scss',
      },
      */
    }),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  }
})
```

When I run the `npm run build`, it generates only js files as expected, when I open the index.html and click on the 'About' link, it tries loading some AboutView-xxxxxx.css, which is not generated.

I assume that this plugin injects css in js, but does not remove a potential import for vuetify css files?
Any idea / help would be appreciated. I'm happy to provide more info if needed.

**Comment by marco-prontera** [comment]
Hi, thank you for reporting! I will check this soon. In the mean time, are you sure that the file is generated through the standard flow of Vite? Because I think if something is created through external functionality the file can be generated outside the output bundle managed inside the hook used for this plugin. If you can provide a link to a project with the same problem you have I will try and fix it if I can

**Comment by marco-prontera** [comment]
Hi, thank you for reporting! I will check this soon. If you can provide a link to a project with the same problem you have I will try and fix it if I can

**Comment by plaskbar** [comment]
This should reproduce it like I described above: https://github.com/plaskbar/vite-plugin-css-injected-by-js-bug-reproducer

If you need anything else, happy to provide. I just don't really know how to debug this myself

**Comment by marco-prontera** [comment]
Hi @plaskbar I tried it with the latest v3.1.1 that I released and it works because by deleting the Vite metadata configuration for the css assets the Vue plugin will only add the js import code so the page now won't try to fetch none css. Thanks for reporting the issue, update the plugin to v3.1.1 and you'll see what I'm saying. Hope this helps, let me know if you run into any other issues!

**Comment by plaskbar** [comment]
Yeah ok I could have searched for a newer version first, sorry :sweat_smile: 

Thanks for the help! Works fine with newest version
